### ISSUE TITLE
Not able to login to instagram

### ISSUE THREAD

**Issue by ajduke** [yubozhao/meteor-accounts-instagram#3]
Hi,

On server side, here i did following configuration  -

```
ServiceConfiguration.configurations.remove({
  service: "instagram"
});
ServiceConfiguration.configurations.insert({
  service: "instagram",
  clientId: "<my-client-id>",
  secret: "<my-secret>"
});
```

and on button click i am doing following -

```
    Meteor.loginWithInstagram((err, res)->
      console.log 'login failed '+err
    )
```

After i click on button, event is fired and i get consent screen for instagram after that  i authenticate then window disappears but i get following error on server console 
Thus not able to login

```
W20141115-00:03:38.226(5.5) (oauth_server.js:78) Unable to parse state from OAuth query: îÞ»>üô¡æz±´Üàõ2#IWÅÀ?¶²U9·
W20141115-00:03:38.234(5.5) (oauth_server.js:78) Unable to parse state from OAuth query: îÞ»>üô¡æz±´Üàõ2#IWÅÀ?¶²U9·
W20141115-00:03:38.235(5.5) (oauth_server.js:78) Unable to parse state from OAuth query: îÞ»>üô¡æz±´Üàõ2#IWÅÀ?¶²U9·
W20141115-00:03:38.236(5.5) (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with Instagram. failed [400] {"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI doesn't match original redirect URI"}
I20141115-00:03:38.667(5.5)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Instagram. failed [400] {"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI doesn't match original redirect URI"}
I20141115-00:03:38.668(5.5)?     at getTokenResponse (packages/bozhao:accounts-instagram/instagram_server.js:50)
I20141115-00:03:38.668(5.5)?     at Object.ServiceConfiguration.configurations.findOne.service [as handleOauthRequest] (packages/bozhao:accounts-instagram/instagram_server.js:5)
I20141115-00:03:38.668(5.5)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8)
I20141115-00:03:38.669(5.5)?     at middleware (packages/oauth/oauth_server.js:173)
I20141115-00:03:38.669(5.5)?     at packages/oauth/oauth_server.js:146
```

Can you look into it and let me know.

Thanks,
ajduke

**Comment by hamzamu** [comment]
Hello this might be strange but i have the same issue . 


```
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Instagram. failed [400] {\"code\": 400, \"error_type\": \"OAuthException\", \"error_message\": \"No matching code found.\"}","time":{"$date":1430391236278},"level":"warn"}
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Instagram. failed [400] {"code": 400, "error_type": "OAuthException", "error_message": "No matching code found."}
    at getTokenResponse (packages/bozhao:accounts-instagram/instagram_server.js:46:1)
    at Object.ServiceConfiguration.configurations.findOne.service [as handleOauthRequest] (packages/bozhao:accounts-instagram/instagram_server.js:5:1)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
    at middleware (packages/oauth/oauth_server.js:173:1)
    at packages/oauth/oauth_server.js:146:1

```

I am using : bozhao:accounts-instagram     0.2.0  Instagram account login for meteor 

and link-accounts 1.1.3

**Comment by landland** [comment]
@yubozhao I'm also running into this issue on version 0.2.0. Any ideas?
